# Generated by Django 2.2.5 on 2020-03-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='substitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='survival.Substitution'),
        ),
    ]
