# Generated by Django 2.2.5 on 2020-03-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survival', '0002_auto_20200321_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
